services:
  postgresql:
    image: postgres:16
    command: -c fsync=off -c full_page_writes=off
    environment:
      POSTGRES_USER: "${PGUSER?}"
      POSTGRES_PASSWORD: "${PGPASSWORD?}"
      EXTRA_USER_DBS:
        "${KUMARA_WEB_API_DB_USERNAME?}:${KUMARA_WEB_API_DB_PASSWORD?}|\
        ${TEST_KUMARA_WEB_API_DB_USERNAME?}:${TEST_KUMARA_WEB_API_DB_PASSWORD?}:${TEST_KUMARA_WEB_API_DB_USERNAME?}_{1..5}|\
        ${KUMARA_CORE_DB_USERNAME?}:${KUMARA_CORE_DB_PASSWORD?}|\
        ${TEST_KUMARA_CORE_DB_USERNAME?}:${TEST_KUMARA_CORE_DB_PASSWORD?}|\
        ${KUMARA_SEARCH_DB_USERNAME?}:${KUMARA_SEARCH_DB_PASSWORD?}|\
        ${TEST_KUMARA_SEARCH_DB_USERNAME?}:${TEST_KUMARA_SEARCH_DB_PASSWORD?}"
    volumes:
      - .docker/postgresql/health.sh:/health.sh:ro
      - .docker/postgresql/initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - 127.0.0.1:5434:5432
    restart: unless-stopped
    healthcheck:
      test: /health.sh

  mongodb:
    image: "${MONGO_IMAGE?}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME?}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD?}"
      EXTRA_USER_DBS: "${KUMARA_EVENTS_DB_USERNAME?}:${KUMARA_EVENTS_DB_PASSWORD?}"
    volumes:
      - .docker/mongo/health.sh:/health.sh:ro
      - .docker/mongo/initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
    healthcheck:
      test: /health.sh

  elasticsearch:
    image: elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD="${ELASTIC_PASSWORD?}"
    volumes:
      - .docker/elasticsearch/health.sh:/health.sh:ro
    ports:
      - 127.0.0.1:9200:9200
    restart: unless-stopped
    healthcheck:
      test: /health.sh
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 60s
