services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: "${PGUSER?}"
      POSTGRES_PASSWORD: "${PGPASSWORD?}"
      EXTRA_USER_DBS:
        "${KUMARA_WEB_API_DB_USERNAME?}:${KUMARA_WEB_API_DB_PASSWORD?}|\
        ${TEST_KUMARA_WEB_API_DB_USERNAME?}:${TEST_KUMARA_WEB_API_DB_PASSWORD?}"
    volumes:
      - .docker/postgresql/health.sh:/health.sh:ro
      - .docker/postgresql/initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - 127.0.0.1:5434:5432
    restart: unless-stopped
    healthcheck:
      test: /health.sh

  mongodb:
    image: "${MONGO_IMAGE?}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME?}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD?}"
      EXTRA_USER_DBS: "${KUMARA_EVENTS_DB_USERNAME?}:${KUMARA_EVENTS_DB_PASSWORD?}"
    volumes:
      - .docker/mongo/health.sh:/health.sh:ro
      - .docker/mongo/initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
    healthcheck:
      test: /health.sh
