services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: "${PGUSER?}"
      POSTGRES_PASSWORD: "${PGPASSWORD?}"
    volumes:
      - .docker/postgresql/health.sh:/health.sh:ro
    ports:
      - 127.0.0.1:5434:5432
    restart: unless-stopped
    healthcheck:
      test: /health.sh

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME?}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD?}"
    volumes:
      - .docker/mongo/health.sh:/health.sh:ro
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
    healthcheck:
      test: /health.sh
