[tools]
dotnet = "9"

[tasks.rider-test-env]
description = "populate Rider Test Runner environment variables"
run = "dotnet run --project script/MiseRiderTestRunnerEnv Kumara.sln.DotSettings.user"

[env]
PGHOST="127.0.0.1"
PGPORT="5434"
PGUSER="kumara-admin"
PGPASSWORD="{{exec(command='script/make-secret pgpassword', cache_key='pgpassword', cache_duration='1h')}}"

KUMARA_WEB_API_DB_USERNAME="kumara-web-api"
KUMARA_WEB_API_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_WEB_API_DB_PASSWORD', cache_key='KUMARA_WEB_API_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraWebApiDB="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.KUMARA_WEB_API_DB_USERNAME}};Username={{env.KUMARA_WEB_API_DB_USERNAME}};Password={{env.KUMARA_WEB_API_DB_PASSWORD}}"

TEST_KUMARA_WEB_API_DB_USERNAME="kumara-web-api-test"
TEST_KUMARA_WEB_API_DB_PASSWORD="{{exec(command='script/make-secret TEST_KUMARA_WEB_API_DB_PASSWORD', cache_key='TEST_KUMARA_WEB_API_DB_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraWebApiDB_TEMPLATE="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.TEST_KUMARA_WEB_API_DB_USERNAME}}_{1..5};Username={{env.TEST_KUMARA_WEB_API_DB_USERNAME}};Password={{env.TEST_KUMARA_WEB_API_DB_PASSWORD}}"

KUMARA_CORE_DB_USERNAME="kumara-core"
KUMARA_CORE_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_CORE_DB_PASSWORD', cache_key='KUMARA_CORE_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraCoreDB="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.KUMARA_CORE_DB_USERNAME}};Username={{env.KUMARA_CORE_DB_USERNAME}};Password={{env.KUMARA_CORE_DB_PASSWORD}}"

TEST_KUMARA_CORE_DB_USERNAME="kumara-core-test"
TEST_KUMARA_CORE_DB_PASSWORD="{{exec(command='script/make-secret TEST_KUMARA_CORE_DB_PASSWORD', cache_key='TEST_KUMARA_CORE_DB_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraCoreDB_TEMPLATE="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.TEST_KUMARA_CORE_DB_USERNAME}}_{1..5};Username={{env.TEST_KUMARA_CORE_DB_USERNAME}};Password={{env.TEST_KUMARA_CORE_DB_PASSWORD}}"

KUMARA_SEARCH_DB_USERNAME="kumara-search"
KUMARA_SEARCH_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_SEARCH_DB_PASSWORD', cache_key='KUMARA_SEARCH_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraSearchDB="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.KUMARA_SEARCH_DB_USERNAME}};Username={{env.KUMARA_SEARCH_DB_USERNAME}};Password={{env.KUMARA_SEARCH_DB_PASSWORD}}"

TEST_KUMARA_SEARCH_DB_USERNAME="kumara-search-test"
TEST_KUMARA_SEARCH_DB_PASSWORD="{{exec(command='script/make-secret TEST_KUMARA_SEARCH_DB_PASSWORD', cache_key='TEST_KUMARA_SEARCH_DB_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraSearchDB_TEMPLATE="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.TEST_KUMARA_SEARCH_DB_USERNAME}};Username={{env.TEST_KUMARA_SEARCH_DB_USERNAME}};Password={{env.TEST_KUMARA_SEARCH_DB_PASSWORD}}"

MONGO_IMAGE="mongo:8"
MONGO_INITDB_ROOT_USERNAME="kumara-admin"
MONGO_INITDB_ROOT_PASSWORD="{{exec(command='script/make-secret MONGO_ROOT_PASSWORD', cache_key='MONGO_ROOT_PASSWORD', cache_duration='1h')}}"

KUMARA_EVENTS_DB_USERNAME="kumara-events"
KUMARA_EVENTS_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_EVENTS_DB_PASSWORD', cache_key='KUMARA_EVENTS_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraEventSourceDB="mongodb://{{env.KUMARA_EVENTS_DB_USERNAME}}:{{env.KUMARA_EVENTS_DB_PASSWORD}}@localhost:27017/{{env.KUMARA_EVENTS_DB_USERNAME}}?authSource=admin"

ELASTIC_PASSWORD="{{exec(command='script/make-secret ELASTIC_PASSWORD', cache_key='ELASTIC_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraSearchES = "http://elastic:{{env.ELASTIC_PASSWORD}}@localhost:9200"

TEST_ELASTIC_PASSWORD="{{exec(command='script/make-secret TEST_ELASTIC_PASSWORD', cache_key='TEST_ELASTIC_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraSearchES = "http://elastic:{{env.TEST_ELASTIC_PASSWORD}}@localhost:9201"
