[tools]
dotnet = "9"
sops = "latest"
age = "latest"
node = "24"
"npm:foreman" = "latest"

[settings.sops]
age_key_file = "{{config_root}}/.local/sops/age.txt"
# NOTE: Disable strict mode so we can bootstrap our secrets using mise t setup:secrets
strict = false

[tasks."setup:credprovider"]
outputs = "{{env.HOME}}/.nuget/plugins/netcore/CredentialProvider.Microsoft/"
run = 'sh -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh)"'
[tasks."setup:tool-restore"]
run = "dotnet tool restore"
[tasks."setup:nuget-restore"]
run = "dotnet restore --interactive"
[tasks."setup:certs"]
run = """
dotnet dev-certs https
dotnet dev-certs https --trust
"""
[tasks."setup:secrets"]
outputs = "{{config_root}}/.local/sops/age.txt"
run = "op read 'op://E7 Developers/SYNCHRO EVM - SOPS - Development/age.txt' > '{{config_root}}/.local/sops/age.txt'"
[tasks.setup]
depends = ["setup:credprovider", "setup:tool-restore", "setup:nuget-restore", "setup:certs", "setup:secrets"]

[tasks."dev:services"]
description = "run service dependencies using docker"
run = "script/dcl up -d --wait"
[tasks."dev:edit-secrets"]
description = "edit the encrypted dev secrets"
run = "SOPS_AGE_KEY_FILE={{config_root}}/.local/sops/age.txt sops edit .env.json"

[tasks.test]
depends = ["dev:services"]
run = "dotnet test"

[tasks.build]
run = "dotnet build"
[tasks.start]
description = "run services without reloading"
depends = ["dev:services", "build"]
run = "nf start"
[tasks.dev]
description = "run services with reloading"
depends = ["dev:services", "build"]
run = "nf --procfile Procfile.dev start"

[tasks.doctor]
description = "check for possible problems"
depends = ["setup"]
run = "mise run test"

[tasks.rider-test-env]
description = "populate Rider Test Runner environment variables"
run = "dotnet run --project script/MiseRiderTestRunnerEnv Kumara.sln.DotSettings.user"

[env]
_.file = { path = ".env.json", redact = true }

# NOTE provide defaults so we can at least run mise to make the secrets work
IMS_API_SECRET = "{{ env.IMS_API_SECRET | default(value=\"missing .env.json\") }}"
IMS_CLIENT_SECRET = "{{ env.IMS_CLIENT_SECRET | default(value=\"missing .env.json\") }}"
IMS_BACKGROUND_CLIENT_SECRET = "{{ env.IMS_BACKGROUND_CLIENT_SECRET | default(value=\"missing .env.json\") }}"

PGHOST="127.0.0.1"
PGPORT="5434"
PGUSER="kumara-admin"
PGPASSWORD="{{exec(command='script/make-secret pgpassword', cache_key='pgpassword', cache_duration='1h')}}"
CITUS_PGPORT="5435"

KUMARA_WEB_API_DB_USERNAME="kumara-web-api"
KUMARA_WEB_API_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_WEB_API_DB_PASSWORD', cache_key='KUMARA_WEB_API_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraWebApiDB="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.KUMARA_WEB_API_DB_USERNAME}};Username={{env.KUMARA_WEB_API_DB_USERNAME}};Password={{env.KUMARA_WEB_API_DB_PASSWORD}}"

TEST_KUMARA_WEB_API_DB_USERNAME="kumara-web-api-test"
TEST_KUMARA_WEB_API_DB_PASSWORD="{{exec(command='script/make-secret TEST_KUMARA_WEB_API_DB_PASSWORD', cache_key='TEST_KUMARA_WEB_API_DB_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraWebApiDB_TEMPLATE="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.TEST_KUMARA_WEB_API_DB_USERNAME}}_{1..5};Username={{env.TEST_KUMARA_WEB_API_DB_USERNAME}};Password={{env.TEST_KUMARA_WEB_API_DB_PASSWORD}}"

KUMARA_CORE_DB_USERNAME="kumara-core"
KUMARA_CORE_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_CORE_DB_PASSWORD', cache_key='KUMARA_CORE_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraCoreDB="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.KUMARA_CORE_DB_USERNAME}};Username={{env.KUMARA_CORE_DB_USERNAME}};Password={{env.KUMARA_CORE_DB_PASSWORD}}"

TEST_KUMARA_CORE_DB_USERNAME="kumara-core-test"
TEST_KUMARA_CORE_DB_PASSWORD="{{exec(command='script/make-secret TEST_KUMARA_CORE_DB_PASSWORD', cache_key='TEST_KUMARA_CORE_DB_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraCoreDB_TEMPLATE="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.TEST_KUMARA_CORE_DB_USERNAME}}_{1..5};Username={{env.TEST_KUMARA_CORE_DB_USERNAME}};Password={{env.TEST_KUMARA_CORE_DB_PASSWORD}}"

KUMARA_SEARCH_DB_USERNAME="kumara-search"
KUMARA_SEARCH_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_SEARCH_DB_PASSWORD', cache_key='KUMARA_SEARCH_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraSearchDB="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.KUMARA_SEARCH_DB_USERNAME}};Username={{env.KUMARA_SEARCH_DB_USERNAME}};Password={{env.KUMARA_SEARCH_DB_PASSWORD}}"

TEST_KUMARA_SEARCH_DB_USERNAME="kumara-search-test"
TEST_KUMARA_SEARCH_DB_PASSWORD="{{exec(command='script/make-secret TEST_KUMARA_SEARCH_DB_PASSWORD', cache_key='TEST_KUMARA_SEARCH_DB_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraSearchDB_TEMPLATE="Host={{env.PGHOST}};Port={{env.PGPORT}};Database={{env.TEST_KUMARA_SEARCH_DB_USERNAME}};Username={{env.TEST_KUMARA_SEARCH_DB_USERNAME}};Password={{env.TEST_KUMARA_SEARCH_DB_PASSWORD}}"

ELASTIC_PASSWORD="{{exec(command='script/make-secret ELASTIC_PASSWORD', cache_key='ELASTIC_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraSearchES = "http://elastic:{{env.ELASTIC_PASSWORD}}@localhost:9200"

TEST_ELASTIC_PASSWORD="{{exec(command='script/make-secret TEST_ELASTIC_PASSWORD', cache_key='TEST_ELASTIC_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraSearchES = "http://elastic:{{env.TEST_ELASTIC_PASSWORD}}@localhost:9201"

OpenIdConnect__ApiSecret = "{{env.IMS_API_SECRET}}"
OpenIdConnect__DelegationClientSecret = "{{env.IMS_CLIENT_SECRET}}"

IMS_BACKGROUND_CLIENT_SECRET_PERCENT_ENCODED = "{{env.IMS_BACKGROUND_CLIENT_SECRET | urlencode}}"

KUMARA_EVENT_SOURCE_DB_USERNAME="kumara-event-source"
KUMARA_EVENT_SOURCE_DB_PASSWORD="{{exec(command='script/make-secret KUMARA_EVENT_SOURCE_DB_PASSWORD', cache_key='KUMARA_EVENT_SOURCE_DB_PASSWORD', cache_duration='1h')}}"
ConnectionStrings__KumaraEventSourceDB="Host={{env.PGHOST}};Port={{env.CITUS_PGPORT}};Database={{env.KUMARA_EVENT_SOURCE_DB_USERNAME}};Username={{env.KUMARA_EVENT_SOURCE_DB_USERNAME}};Password={{env.KUMARA_EVENT_SOURCE_DB_PASSWORD}}"

TEST_KUMARA_EVENT_SOURCE_DB_USERNAME="kumara-event-source-test"
TEST_KUMARA_EVENT_SOURCE_DB_PASSWORD="{{exec(command='script/make-secret TEST_KUMARA_EVENT_SOURCE_DB_PASSWORD', cache_key='TEST_KUMARA_EVENT_SOURCE_DB_PASSWORD', cache_duration='1h')}}"
TEST_ConnectionStrings__KumaraEventSourceDB_TEMPLATE="Host={{env.PGHOST}};Port={{env.CITUS_PGPORT}};Database={{env.TEST_KUMARA_EVENT_SOURCE_DB_USERNAME}}_{1..5};Username={{env.TEST_KUMARA_EVENT_SOURCE_DB_USERNAME}};Password={{env.TEST_KUMARA_EVENT_SOURCE_DB_PASSWORD}}"

SERVICE_SWAGGER_SCORECARD_PASSWORD="{{exec(command='script/make-secret SERVICE_SWAGGER_SCORECARD_PASSWORD', cache_key='SERVICE_SWAGGER_SCORECARD_PASSWORD', cache_duration='1h')}}"
SwaggerLoginMiddleware__SwaggerScorecardSecret="{{env.SERVICE_SWAGGER_SCORECARD_PASSWORD}}"
