{{- if (get .Values "ingress" | default dict).enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "metadata" . | nindent 2 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "name" . }}
                port:
                  name: http
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
