apiVersion: v1
kind: Service
metadata:
  {{- include "metadata" . | nindent 2 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
