# Copyright (c) Bentley Systems, Incorporated. All rights reserved.

@IMS_BaseURL = https://qa-ims.bentley.com
@Kumara_BaseURL = https://localhost:7029

# NOTE: See file://./Database/DbSeeder.cs
@Seed_iTwin1_id = 10000000-0000-0000-0000-000000000000
@QA_iTwin_id = 45dcf082-4fb9-4e92-96f0-4fcedd3fb1af

@client_id = {{$processEnv IMS_BACKGROUND_CLIENT_ID}}
@client_secret = {{$processEnv IMS_BACKGROUND_CLIENT_SECRET}}
@scope = synchro-evm

# TODO: %encoding of variables is in bleeding edge of rest client
@%client_secret = {{$processEnv IMS_BACKGROUND_CLIENT_SECRET_PERCENT_ENCODED}}

# @name IMS_token
POST {{IMS_BaseURL}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{%client_secret}}
&scope={{scope}}

###

@IMS_JWT = {{IMS_token.response.body.$.access_token}}

# List Activities
GET {{Kumara_BaseURL}}/api/v1/activities?iTwinId={{Seed_iTwin1_id}}
Authorization: Bearer {{IMS_JWT}}
Accept: application/json

###
# Authorization Ping
# @prompt userJWT A JWT with the synchro-evm scope and a principal attached (i.e. has a sub claim)
GET {{Kumara_BaseURL}}/api/v0/authorization/{{QA_iTwin_id}}
Authorization: Bearer {{userJWT}}
Accept: application/json

###
# Swagger with secret
GET {{Kumara_BaseURL}}/swagger/v1/swagger.json?swaggerScorecardSecret={{$processEnv SERVICE_SWAGGER_SCORECARD_PASSWORD}}

###
