# Copyright (c) Bentley Systems, Incorporated. All rights reserved.
@Kumara_EventSource_HostAddress = http://localhost:5220

### without events
POST {{Kumara_EventSource_HostAddress}}/events
Content-Type: application/cloudevents-batch+json

[]

### With events
POST {{Kumara_EventSource_HostAddress}}/events
Content-Type: application/cloudevents-batch+json

[
  {
    "specversion": "1.0",
    "type": "test.created.v1",
    "source": "/events/test",
    "id": "T234-1234-1234",
    "time": "2023-10-01T12:15:00Z",
    "data": {
      "test_string": "Sample Test 1",
      "test_enum": "OptionA",
      "test_integer": 123,
      "event_type_version": "1.0"
    }
  },
  {
    "specversion": "1.0",
    "type": "test.created.v1",
    "source": "/events/test",
    "id": "T234-1234-1235",
    "time": "2023-10-01T12:20:00Z",
    "data": {
      "test_string": "Sample Test 2",
      "test_enum": "OptionB",
      "test_integer": 456,
      "event_type_version": "1.0"
    }
  },
  {
    "specversion": "1.0",
    "type": "test.created.v1",
    "source": "/events/test",
    "id": "T234-1234-1236",
    "time": "2023-10-01T12:25:00Z",
    "data": {
      "test_string": "Sample Test 3",
      "test_enum": "OptionC",
      "test_integer": 789,
      "event_type_version": "1.0"
    }
  }
]

### Get events
GET {{Kumara_EventSource_HostAddress}}/events
Accept: application/cloudevents-batch+json
