// <auto-generated />
using System;
using System.Text.Json;
using Kumara.EventSourceToo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kumara.EventSourceToo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828011750_AddEvents")]
    partial class AddEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kumara.EventSourceToo.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<Instant?>("TriggeredByUserAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_by_user_at");

                    b.Property<Guid?>("TriggeredByUserSubject")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_user_subject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id", "AccountId")
                        .HasName("pk_events");

                    b.HasIndex("ITwinId")
                        .HasDatabaseName("ix_events_itwin_id");

                    b.ToTable("events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
