#!/bin/bash
# Copyright (c) Bentley Systems, Incorporated. All rights reserved.
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <project-name>" >&2
  exit 1
fi
project="$1"

env_file="$(mktemp "${TMPDIR:-/tmp}/synchro-evm-docker.env.XXXXXX")"
trap '{ rm "$env_file"; }' EXIT

component="$(echo "$project" | cut -d '.' -f2 | sed 's/\([a-z0-9]\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]')"

bcsm_values_path="helm/values.bcsm.$component.yaml"
secrets_pattern="$(yq '.env // {} | keys [], .envSecret // {} | keys[]' "$bcsm_values_path" | sed -e 's/^/^/' -e 's/$/=/' | paste -sd'|' -)"
mise env -D |
  grep -E "$secrets_pattern" |
  sed -E 's/localhost|127\.0\.0\.1/host.docker.internal/g' \
  > "$env_file"

shopt -s nullglob
devcerts=()
for devcert in ~/.aspnet/dev-certs/https/aspnetcore-localhost-*.pfx; do
  devcerts+=("$devcert")
done
shopt -u nullglob

if [ ${#devcerts[@]} -ne 1 ]; then
  echo 'Could not find development certificate for ASP.Net.' >&2
  exit 1
fi

urls=$(jq -r '.profiles | to_entries[0].value.applicationUrl' "$project/Properties/launchSettings.json" | sed 's/localhost/+/g')

publish_args=()
IFS=';' read -ra endpoints <<< "$urls"
for endpoint in "${endpoints[@]}"; do
  port=$(echo "$endpoint" | grep -Eo '[0-9]+$')
  publish_args+=(--publish "127.0.0.1:$port:$port")
done

docker run \
  --rm -it \
  --volume "${devcerts[0]}":/mnt/devcert.pfx:ro \
  --env-file "$env_file" \
  --env ASPNETCORE_ENVIRONMENT=Development \
  --env ASPNETCORE_HTTP_PORTS= \
  --env ASPNETCORE_URLS="$urls" \
  --env ASPNETCORE_Kestrel__Certificates__Default__Path=/mnt/devcert.pfx \
  "${publish_args[@]}" \
  --workdir "/app/$project" \
  synchro-evm \
  "$project.dll"
