#!/bin/bash
# Copyright (c) Bentley Systems, Incorporated. All rights reserved.
set -euo pipefail

key="${1?key required}"

values_dir="$(git rev-parse --git-dir)/.make-secret-data"
mkdir -p "$values_dir"

value_path="$values_dir/$key"
if ! [ -s "$value_path" ]; then
  openssl rand -hex 16 > "$value_path"
fi

cat "$value_path"
