image:
  repository: #{Process.ACR.RegistryFullName}
  name: #{Process.ACR.RepositoryName}
  tag: #{Build.BuildNumber}
  pullPolicy: #{Process.DHC.Image.PullPolicy}
  pullSecretName: #{Process.ACR.RegistrySecretName}
replicaCount: #{Process.DHC.ReplicaCount}
autoscaling:
  enabled: #{Process.HPA.Enabled}
  minReplicas: #{Process.HPA.MinReplicas}
  maxReplicas: #{Process.HPA.MaxReplicas}
  targetCPUUtilizationPercentage: #{Process.HPA.AvgCPUUtilization}
  targetMemoryUtilizationPercentage: #{Process.HPA.AvgMemoryUtilization}
