// <auto-generated />
using System;
using Kumara.WebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kumara.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250626053251_AddFakeITwins")]
    partial class AddFakeITwins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kumara.WebApi.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControlAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("control_account_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PlannedFinish")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_finish");

                    b.Property<DateTimeOffset?>("PlannedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("_actualFinish")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_finish");

                    b.Property<bool?>("_actualFinishHasTime")
                        .HasColumnType("boolean")
                        .HasColumnName("actual_finish_has_time");

                    b.Property<DateTimeOffset?>("_actualStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start");

                    b.Property<bool?>("_actualStartHasTime")
                        .HasColumnType("boolean")
                        .HasColumnName("actual_start_has_time");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("ControlAccountId")
                        .HasDatabaseName("ix_activities_control_account_id");

                    b.HasIndex("ITwinId")
                        .HasDatabaseName("ix_activities_itwin_id");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.ControlAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualFinish")
                        .HasColumnType("date")
                        .HasColumnName("actual_finish");

                    b.Property<DateOnly?>("ActualStart")
                        .HasColumnType("date")
                        .HasColumnName("actual_start");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("PlannedFinish")
                        .HasColumnType("date")
                        .HasColumnName("planned_finish");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date")
                        .HasColumnName("planned_start");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_control_accounts");

                    b.HasIndex("ITwinId")
                        .HasDatabaseName("ix_control_accounts_itwin_id");

                    b.ToTable("control_accounts", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.FakeITwin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_owner_id");

                    b.Property<int?>("AccountOwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("account_owner_type");

                    b.Property<bool?>("AllowExternalUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_external_users");

                    b.Property<int?>("AuthMode")
                        .HasColumnType("integer")
                        .HasColumnName("auth_mode");

                    b.Property<string>("BillingCountry")
                        .HasColumnType("text")
                        .HasColumnName("billing_country");

                    b.Property<string>("Class")
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<Guid?>("DataCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_center_id");

                    b.Property<string>("DataCenterLocation")
                        .HasColumnType("text")
                        .HasColumnName("data_center_location");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("GeographicLocation")
                        .HasColumnType("text")
                        .HasColumnName("geographic_location");

                    b.Property<string>("IanaTimeZone")
                        .HasColumnType("text")
                        .HasColumnName("iana_time_zone");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool?>("IsTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_template");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date_time");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("SolutionType")
                        .HasColumnType("text")
                        .HasColumnName("solution_type");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubClass")
                        .HasColumnType("text")
                        .HasColumnName("sub_class");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid?>("iTwinAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_account_id");

                    b.HasKey("Id")
                        .HasName("pk_fake_itwins");

                    b.ToTable("fake_itwins", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("QuantityUnitOfMeasureId")
                        .HasColumnType("uuid")
                        .HasColumnName("quantity_unit_of_measure_id");

                    b.Property<Guid>("ResourceRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_role_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("ITwinId")
                        .HasDatabaseName("ix_materials_itwin_id");

                    b.HasIndex("QuantityUnitOfMeasureId")
                        .HasDatabaseName("ix_materials_quantity_unit_of_measure_id");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.MaterialActivityAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<decimal>("QuantityAtComplete")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_at_complete");

                    b.Property<Guid>("QuantityUnitOfMeasureId")
                        .HasColumnType("uuid")
                        .HasColumnName("quantity_unit_of_measure_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_material_activity_allocations");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_material_activity_allocations_activity_id");

                    b.HasIndex("ITwinId")
                        .HasDatabaseName("ix_material_activity_allocations_itwin_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_material_activity_allocations_material_id");

                    b.HasIndex("QuantityUnitOfMeasureId")
                        .HasDatabaseName("ix_material_activity_allocations_quantity_unit_of_measure_id");

                    b.ToTable("material_activity_allocations", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.ProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<DateOnly>("ProgressDate")
                        .HasColumnType("date")
                        .HasColumnName("progress_date");

                    b.Property<decimal>("QuantityDelta")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_delta");

                    b.Property<Guid>("QuantityUnitOfMeasureId")
                        .HasColumnType("uuid")
                        .HasColumnName("quantity_unit_of_measure_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_progress_entries");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_progress_entries_activity_id");

                    b.HasIndex("ITwinId")
                        .HasDatabaseName("ix_progress_entries_itwin_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_progress_entries_material_id");

                    b.HasIndex("QuantityUnitOfMeasureId")
                        .HasDatabaseName("ix_progress_entries_quantity_unit_of_measure_id");

                    b.ToTable("progress_entries", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.ProgressSummary", b =>
                {
                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid>("QuantityUnitOfMeasureId")
                        .HasColumnType("uuid")
                        .HasColumnName("quantity_unit_of_measure_id");

                    b.Property<decimal>("QuantityAtComplete")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_at_complete");

                    b.Property<decimal>("QuantityToComplete")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_to_complete");

                    b.Property<decimal>("QuantityToDate")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_to_date");

                    b.HasKey("ITwinId", "ActivityId", "MaterialId", "QuantityUnitOfMeasureId");

                    b.ToTable((string)null);

                    b.ToView("progress_summaries", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<object>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.HasIndex("ITwinId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_settings_itwin_id_key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_units_of_measure");

                    b.HasIndex("ITwinId")
                        .HasDatabaseName("ix_units_of_measure_itwin_id");

                    b.ToTable("units_of_measure", (string)null);
                });

            modelBuilder.Entity("Kumara.WebApi.Models.Activity", b =>
                {
                    b.HasOne("Kumara.WebApi.Models.ControlAccount", "ControlAccount")
                        .WithMany()
                        .HasForeignKey("ControlAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_control_accounts_control_account_id");

                    b.Navigation("ControlAccount");
                });

            modelBuilder.Entity("Kumara.WebApi.Models.Material", b =>
                {
                    b.HasOne("Kumara.WebApi.Models.UnitOfMeasure", "QuantityUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("QuantityUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_materials_units_of_measure_quantity_unit_of_measure_id");

                    b.Navigation("QuantityUnitOfMeasure");
                });

            modelBuilder.Entity("Kumara.WebApi.Models.MaterialActivityAllocation", b =>
                {
                    b.HasOne("Kumara.WebApi.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_activity_allocations_activities_activity_id");

                    b.HasOne("Kumara.WebApi.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_activity_allocations_materials_material_id");

                    b.HasOne("Kumara.WebApi.Models.UnitOfMeasure", "QuantityUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("QuantityUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_activity_allocations_units_of_measure_quantity_uni");

                    b.Navigation("Activity");

                    b.Navigation("Material");

                    b.Navigation("QuantityUnitOfMeasure");
                });

            modelBuilder.Entity("Kumara.WebApi.Models.ProgressEntry", b =>
                {
                    b.HasOne("Kumara.WebApi.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_entries_activities_activity_id");

                    b.HasOne("Kumara.WebApi.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_entries_materials_material_id");

                    b.HasOne("Kumara.WebApi.Models.UnitOfMeasure", "QuantityUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("QuantityUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_entries_units_of_measure_quantity_unit_of_measure_");

                    b.Navigation("Activity");

                    b.Navigation("Material");

                    b.Navigation("QuantityUnitOfMeasure");
                });

            modelBuilder.Entity("Kumara.WebApi.Models.ProgressSummary", b =>
                {
                    b.OwnsMany("Kumara.WebApi.Models.RecentProgressEntry", "RecentProgressEntries", b1 =>
                        {
                            b1.Property<Guid>("ProgressSummaryITwinId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProgressSummaryActivityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProgressSummaryMaterialId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProgressSummaryQuantityUnitOfMeasureId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("__synthesized_ordinal");

                            b1.Property<string>("CreatedAt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "created_at");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasAnnotation("Relational:JsonPropertyName", "id");

                            b1.Property<DateOnly>("ProgressDate")
                                .HasColumnType("date")
                                .HasAnnotation("Relational:JsonPropertyName", "progress_date");

                            b1.Property<decimal>("QuantityDelta")
                                .HasColumnType("numeric")
                                .HasAnnotation("Relational:JsonPropertyName", "quantity_delta");

                            b1.Property<string>("UpdatedAt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                            b1.HasKey("ProgressSummaryITwinId", "ProgressSummaryActivityId", "ProgressSummaryMaterialId", "ProgressSummaryQuantityUnitOfMeasureId", "__synthesizedOrdinal");

                            b1.ToTable((string)null);

                            b1.ToView("progress_summaries");

                            b1.ToJson("recent_progress_entries");

                            b1.WithOwner()
                                .HasForeignKey("ProgressSummaryITwinId", "ProgressSummaryActivityId", "ProgressSummaryMaterialId", "ProgressSummaryQuantityUnitOfMeasureId");
                        });

                    b.Navigation("RecentProgressEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
