// <auto-generated />
using System;
using Kumara.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kumara.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501131756_AddMaterials")]
    partial class AddMaterials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kumara.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualFinish")
                        .HasColumnType("date")
                        .HasColumnName("actual_finish");

                    b.Property<DateOnly?>("ActualStart")
                        .HasColumnType("date")
                        .HasColumnName("actual_start");

                    b.Property<Guid>("ControlAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("control_account_id");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("PlannedFinish")
                        .HasColumnType("date")
                        .HasColumnName("planned_finish");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date")
                        .HasColumnName("planned_start");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("ControlAccountId")
                        .HasDatabaseName("ix_activities_control_account_id");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("Kumara.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Kumara.Models.ControlAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualFinish")
                        .HasColumnType("date")
                        .HasColumnName("actual_finish");

                    b.Property<DateOnly?>("ActualStart")
                        .HasColumnType("date")
                        .HasColumnName("actual_start");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("PlannedFinish")
                        .HasColumnType("date")
                        .HasColumnName("planned_finish");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date")
                        .HasColumnName("planned_start");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_control_accounts");

                    b.ToTable("control_accounts", (string)null);
                });

            modelBuilder.Entity("Kumara.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("QuantityUnitOfMeasureId")
                        .HasColumnType("uuid")
                        .HasColumnName("quantity_unit_of_measure_id");

                    b.Property<Guid>("ResourceRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_role_id");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("QuantityUnitOfMeasureId")
                        .HasDatabaseName("ix_materials_quantity_unit_of_measure_id");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("Kumara.Models.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ITwinId")
                        .HasColumnType("uuid")
                        .HasColumnName("itwin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_units_of_measure");

                    b.ToTable("units_of_measure", (string)null);
                });

            modelBuilder.Entity("Kumara.Models.Activity", b =>
                {
                    b.HasOne("Kumara.Models.ControlAccount", "ControlAccount")
                        .WithMany()
                        .HasForeignKey("ControlAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_control_accounts_control_account_id");

                    b.Navigation("ControlAccount");
                });

            modelBuilder.Entity("Kumara.Models.Material", b =>
                {
                    b.HasOne("Kumara.Models.UnitOfMeasure", "QuantityUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("QuantityUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_materials_units_of_measure_quantity_unit_of_measure_id");

                    b.Navigation("QuantityUnitOfMeasure");
                });
#pragma warning restore 612, 618
        }
    }
}
