name: $(Date:yyyy.MM.dd).$(Rev:rr)

trigger:
  branches:
    include:
      - main
      - topic/*

pr:
  - main

variables:
  - group: ExternalServiceSecrets
  - name: ProductName
    value: SYNCHRO EVM
  - name: ShortCode
    value: EVM
  - name: GPR_ProductID
    value: 3579
  - name: Mend.ApiKey
    value: $(MendApiKey)
  - name: Mend.UserKey
    value: $(MendServiceAccountKey)
  - name: Mend.UserEmail
    value: $(MendServiceAccountEmail)
  - name: VeracodeAppProfile
    value: $(ProductName) - WebApi ($(ShortCode) - $(GPR_ProductID))
  - name: DotNetVersion
    value: 9.x

resources:
  repositories:
    - repository: MendScan
      type: git
      name: ReleaseServices/MendScan
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    displayName: Build solution
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET sdk'
        inputs:
          packageType: sdk
          version: $(DotNetVersion)

      - task: NuGetAuthenticate@1
        displayName: 'NuGet Authenticate'
        inputs:
          forceReinstallCredentialProvider: true

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          projects: '**/*.sln'
          arguments: '-c Release'

      - task: CopyFiles@2
        inputs:
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Publish built artifacts
        inputs:
          artifactName: built_artifacts
          pathToPublish: $(Build.ArtifactStagingDirectory)

  - job: Run_Tests
    displayName: Run Tests
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - task: UseDotNet@2
        displayName: Use .NET SDK
        inputs:
          packageType: sdk
          version: $(DotNetVersion)

      - task: CmdLine@2
        displayName: Set environment
        inputs:
          script: |
            .azure-pipelines/script/set-mise-env

      - task: CmdLine@2
        displayName: Start PostgreSQL container
        inputs:
          script: |
            script/dcl up --detach --wait postgresql

      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: test
          arguments: >
            --collect "Code Coverage"
            --
            --report-trx
            --results-directory "$(Agent.TempDirectory)"

  - job: Check_Copyright
    displayName: Check Copyright Notice
    steps:
      - checkout: self
        fetchDepth: 0
      - script: |
          .azure-pipelines/script/check-copyright
        displayName: Check Copyright Notice

  - job: Check_Code_Formatting
    displayName: Check Code Formatting
    steps:
      - task: UseDotNet@2
        displayName: Use .NET SDK
        inputs:
          packageType: sdk
          version: $(DotNetVersion)

      - task: DotNetCoreCLI@2
        displayName: Install dotnet tools
        inputs:
          command: custom
          custom: tool
          arguments: restore

      - task: DotNetCoreCLI@2
        displayName: Check Code Formatting (csharpier)
        inputs:
          command: custom
          custom: csharpier
          arguments: --check .

      - task: DotNetCoreCLI@2
        displayName: Check Code Formatting (dotnet format style)
        inputs:
          command: custom
          custom: format
          arguments: style --verify-no-changes --verbosity diagnostic

      - task: DotNetCoreCLI@2
        displayName: Check Code Formatting (dotnet format analyzers)
        inputs:
          command: custom
          custom: format
          arguments: analyzers --verify-no-changes --verbosity diagnostic

  - job: Scans
    displayName: Mend & Veracode Scans
    dependsOn: Build
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    steps:
      - task: UseDotNet@2
        displayName: Use .NET SDK
        inputs:
          packageType: sdk
          version: $(DotNetVersion)

      - task: DownloadBuildArtifacts@0
        displayName: Download built artifacts
        inputs:
          artifactName: built_artifacts
          downloadPath: $(Build.ArtifactStagingDirectory)

      - template: MendScan.yml@MendScan
        parameters:
          MendProductName: $(ProductName) ($(ShortCode) - $(GPR_ProductID))
          MendPathToScan: $(Build.ArtifactStagingDirectory)
          MendConfigPath: $(Build.SourcesDirectory)/.azure-pipelines/mend/SPNG_config.json
          MendSimulateDelete: true

      - task: DotNetCoreCLI@2
        displayName: Publish for Veracode
        inputs:
          command: publish
          arguments: '-o $(Build.ArtifactStagingDirectory)/veracode_artifacts'

      # https://docs.veracode.com/r/Use_YAML_to_Add_Veracode_Analysis_to_Azure_DevOps_Pipelines
      - task: Veracode@3
        inputs:
          ConnectionDetailsSelection: Service Connection
          AnalysisService: AppSec - Veracode
          veracodeAppProfile: $(VeracodeAppProfile)
          version: $(Build.BuildNumber)
          filepath: $(Build.ArtifactStagingDirectory)/veracode_artifacts
          optargs: '-include *.dll'
