name: $(Date:yyyy.MM.dd).$(Rev:rr)

trigger:
  branches:
    include:
      - main
      - topic/*

pr:
  - main

variables:
  - group: ExternalServiceSecrets
  - name: ProductName
    value: SYNCHRO Perform NextGen
  - name: ShortCode
    value: SPNG
  - name: GPR_ProductID
    value: 3579

jobs:
  - job: Run_Tests
    displayName: Run Tests
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET sdk'
        inputs:
          packageType: sdk
          version: 9.x

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          projects: '**/*.sln'
          arguments: '-c Release'

      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: test
          projects: '**/*.sln'
          arguments: '--filter "SYNCHROPerformNextGen.Tests" -c Release --collect "Code coverage"'

  - job: Check_Copyright
    displayName: Check Copyright Notice
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 0
      - script: |
          .azure-pipelines/script/check-copyright
        displayName: Check Copyright Notice
