name: $(Date:yyyy.MM.dd).$(Rev:rr)

trigger:
  branches:
    include:
      - main
      - topic/*

pr:
  - main

variables:
  - group: ExternalServiceSecrets
  - name: ProductName
    value: SYNCHRO Perform NextGen
  - name: ShortCode
    value: SPNG
  - name: GPR_ProductID
    value: 3579
  - name: Mend.ApiKey
    value: $(MendApiKey)
  - name: Mend.UserKey
    value: $(MendServiceAccountKey)
  - name: Mend.UserEmail
    value: $(MendServiceAccountEmail)

resources:
  repositories:
    - repository: MendScan
      type: git
      name: ReleaseServices/MendScan
      ref: refs/heads/main

jobs:
  - job: Build
    displayName: Build solution
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET sdk'
        inputs:
          packageType: sdk
          version: 9.x

      - task: NuGetAuthenticate@1
        displayName: 'NuGet Authenticate'
        inputs:
          forceReinstallCredentialProvider: true

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          projects: '**/*.sln'
          arguments: '-c Release'

      - task: CopyFiles@2
        inputs:
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Publish built artifacts
        inputs:
          artifactName: built_artifacts
          pathToPublish: $(Build.ArtifactStagingDirectory)

  - job: Run_Tests
    displayName: Run Tests
    dependsOn: Build
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: test
          arguments: '--collect "Code Coverage"'

  - job: Check_Copyright
    displayName: Check Copyright Notice
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 0
      - script: |
          .azure-pipelines/script/check-copyright
        displayName: Check Copyright Notice

  - job: Check_Code_Formatting
    displayName: Check Code Formatting
    steps:
      - task: UseDotNet@2
        displayName: Use .NET sdk
        inputs:
          packageType: sdk
          version: 9.x

      - task: DotNetCoreCLI@2
        displayName: Install dotnet format
        inputs:
          command: custom
          custom: tool
          arguments: update -g dotnet-format

      - task: DotNetCoreCLI@2
        displayName: Check Code Formatting
        inputs:
          command: custom
          custom: format
          arguments: --verify-no-changes --verbosity diagnostic

  - job: Mend_Scan
    displayName: Mend Scan
    dependsOn: Build
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download built artifacts
        inputs:
          artifactName: built_artifacts
          downloadPath: $(Build.ArtifactStagingDirectory)

      - template: MendScan.yml@MendScan
        parameters:
          MendProductName: $(ProductName) ($(ShortCode) - $(GPR_ProductID))
          MendPathToScan: $(Build.ArtifactStagingDirectory)
          MendConfigPath: $(Build.SourcesDirectory)/.azure-pipelines/mend/SPNG_config.json
          MendSimulateDelete: true
