name: $(Date:yyyy.MM.dd).$(Rev:rr)

trigger:
  branches:
    include:
      - main
      - topic/*

pr:
  - main

variables:
  - group: ExternalServiceSecrets
  - name: ProductName
    value: SYNCHRO Perform NextGen
  - name: ShortCode
    value: SPNG
  - name: GPR_ProductID
    value: 3579

jobs:
  - job: Build
    displayName: Build solution
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET sdk'
        inputs:
          packageType: sdk
          version: 9.x

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          projects: '**/*.sln'
          arguments: '-c Release'

      - task: CopyFiles@2
        inputs:
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Publish built artifacts
        inputs:
          artifactName: built_artifacts
          pathToPublish: $(Build.ArtifactStagingDirectory)

  - job: Run_Tests
    displayName: Run Tests
    dependsOn: Build
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5
    steps:
      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: test
          arguments: '--collect "Code Coverage"'

  - job: Check_Copyright
    displayName: Check Copyright Notice
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 0
      - script: |
          .azure-pipelines/script/check-copyright
        displayName: Check Copyright Notice
